// GENERATED by tools/generate_docs_site.ts. Do not edit by hand.

import { defineConfig } from "vitepress"

export default defineConfig({
  title: "Bare CRM",
  description: "Tiny CRM kernel with stable APIs and optional extensions.",
  base: process.env.DOCS_BASE ?? "/bare-crm/",
  srcDir: "src",
  cleanUrls: true,
  lastUpdated: true,
  vite: {
    build: {
      target: "esnext",
    },
  },
  themeConfig: {
    logo: undefined,
    nav: [
      { text: "Guide", link: "/quickstart" },
      { text: "Core", link: "/core/architecture" },
      { text: "Advanced", link: "/advanced/plugins" },
      { text: "GitHub", link: "https://github.com/danekm/bare-crm" },
    ],
    sidebar: [
          {
                "text": "Start Here",
                "items": [
                      {
                            "text": "Quickstart",
                            "link": "/quickstart"
                      },
                      {
                            "text": "README",
                            "link": "/start/readme"
                      },
                      {
                            "text": "Contributing",
                            "link": "/start/contributing"
                      },
                      {
                            "text": "Install",
                            "link": "/start/install"
                      },
                      {
                            "text": "Open Source Plan",
                            "link": "/start/open-source"
                      }
                ]
          },
          {
                "text": "Core",
                "collapsed": false,
                "items": [
                      {
                            "text": "Hard Rules",
                            "link": "/core/hard-rules"
                      },
                      {
                            "text": "Architecture",
                            "link": "/core/architecture"
                      },
                      {
                            "text": "Entities",
                            "link": "/core/entities"
                      },
                      {
                            "text": "Write API",
                            "link": "/core/write-api"
                      },
                      {
                            "text": "Read API",
                            "link": "/core/read-api"
                      },
                      {
                            "text": "Event Log",
                            "link": "/core/event-log"
                      },
                      {
                            "text": "Storage API",
                            "link": "/core/storage-api"
                      },
                      {
                            "text": "SQLite",
                            "link": "/core/sqlite"
                      },
                      {
                            "text": "Postgres and Supabase",
                            "link": "/core/postgres-supabase"
                      },
                      {
                            "text": "CLI",
                            "link": "/core/cli"
                      },
                      {
                            "text": "Admin Surface",
                            "link": "/core/admin-surface"
                      },
                      {
                            "text": "Permissions",
                            "link": "/core/permissions"
                      },
                      {
                            "text": "Privacy Safety",
                            "link": "/core/privacy-safety"
                      },
                      {
                            "text": "Conformance",
                            "link": "/core/conformance"
                      },
                      {
                            "text": "Test Portfolio",
                            "link": "/core/test-portfolio"
                      }
                ]
          },
          {
                "text": "Advanced",
                "collapsed": true,
                "items": [
                      {
                            "text": "Import and Export",
                            "link": "/advanced/import-export"
                      },
                      {
                            "text": "Channel Strategy",
                            "link": "/advanced/channel-strategy"
                      },
                      {
                            "text": "App User Lookup",
                            "link": "/advanced/app-user-lookup"
                      },
                      {
                            "text": "Gmail Plugin",
                            "link": "/advanced/gmail-plugin"
                      },
                      {
                            "text": "Instagram Plugin",
                            "link": "/advanced/instagram-plugin"
                      },
                      {
                            "text": "Reddit Plugin",
                            "link": "/advanced/reddit-plugin"
                      },
                      {
                            "text": "Google Tasks Plugin",
                            "link": "/advanced/google-tasks-plugin"
                      },
                      {
                            "text": "Granola Plugin",
                            "link": "/advanced/granola-plugin"
                      },
                      {
                            "text": "Policies and Workflows",
                            "link": "/advanced/policies-workflows"
                      },
                      {
                            "text": "Plugins",
                            "link": "/advanced/plugins"
                      },
                      {
                            "text": "Plugin Development",
                            "link": "/advanced/plugin-development"
                      },
                      {
                            "text": "Plugin Data Safety",
                            "link": "/advanced/plugin-data-safety"
                      },
                      {
                            "text": "Plugin Workbench UI",
                            "link": "/advanced/workbench-ui"
                      },
                      {
                            "text": "Plugin Safety Coverage",
                            "link": "/advanced/plugin-safety-coverage"
                      },
                      {
                            "text": "Extension Host",
                            "link": "/advanced/extension-host"
                      },
                      {
                            "text": "MCP Adapter",
                            "link": "/advanced/mcp"
                      },
                      {
                            "text": "Dashboard Lab",
                            "link": "/advanced/dashboard"
                      },
                      {
                            "text": "Noros Integration",
                            "link": "/advanced/noros"
                      },
                      {
                            "text": "Publishing",
                            "link": "/advanced/publishing"
                      }
                ]
          }
    ],
    search: {
      provider: "local",
    },
    socialLinks: [
      { icon: "github", link: "https://github.com/danekm/bare-crm" },
    ],
  },
})
