const rows = [
  {
    requirement: "Data minimization",
    status: "partial runtime + docs",
    evidence: [
      "tests/plugin_data_safety_runtime.test.ts",
      "tests/bare_gmail_plugin.test.ts",
      "tests/supabase_users_plugin.test.ts",
      "tests/plugin_data_safety_docs.test.ts",
    ],
    note:
      "Gmail ignored/suggested messages do not write records; Supabase copies only mapped safe traits. Full policy enforcement remains per-plugin.",
  },
  {
    requirement: "Workspace isolation",
    status: "runtime tested",
    evidence: [
      "tests/kernel.test.ts",
      "tests/extensions.test.ts",
      "tests/supabase_users_plugin.test.ts",
    ],
    note:
      "Kernel reads/writes, Extension Host state, secrets, profiles, and plugin installs are workspace-scoped.",
  },
  {
    requirement: "Explicit capabilities",
    status: "runtime tested",
    evidence: [
      "tests/kernel.test.ts",
      "tests/extensions.test.ts",
      "tests/bare_gmail_plugin.test.ts",
      "tests/bare_gmail_sync.test.ts",
      "tests/supabase_users_plugin.test.ts",
      "tests/plugins.test.ts",
    ],
    note:
      "Kernel, Extension Host, Gmail, Gmail sync, Supabase lookup, and manifests reject missing or forbidden capabilities.",
  },
  {
    requirement: "Secrets stay out of CRM",
    status: "runtime tested",
    evidence: [
      "tests/plugin_data_safety_runtime.test.ts",
      "tests/extensions.test.ts",
      "tests/privacy_safety.test.ts",
    ],
    note:
      "Supabase service role keys and raw secret-looking fields are asserted absent from CRM records and event snapshots.",
  },
  {
    requirement: "No raw provider payloads",
    status: "runtime tested",
    evidence: [
      "tests/plugin_data_safety_runtime.test.ts",
      "tests/plugin_data_safety_docs.test.ts",
    ],
    note:
      "Gmail raw body/header/label values and unmapped Supabase raw fields are asserted absent from CRM state.",
  },
  {
    requirement: "Auditable writes",
    status: "runtime tested",
    evidence: [
      "tests/plugin_data_safety_runtime.test.ts",
      "tests/kernel.test.ts",
      "tests/admin.test.ts",
      "tests/mcp.test.ts",
    ],
    note:
      "Plugin writes carry plugin actor metadata and stable idempotency keys in Event Log metadata.",
  },
  {
    requirement: "Redacted operational output",
    status: "runtime tested",
    evidence: [
      "tests/privacy_safety.test.ts",
      "tests/admin.test.ts",
      "tests/cli.test.ts",
      "tests/dashboard.test.ts",
    ],
    note:
      "Admin, CLI, and dashboard operational surfaces avoid raw record snapshots or redact private-looking values.",
  },
  {
    requirement: "Idempotency and dedupe",
    status: "runtime tested",
    evidence: [
      "tests/kernel.test.ts",
      "tests/bare_gmail_plugin.test.ts",
      "tests/bare_gmail_sync.test.ts",
      "tests/supabase_users_plugin.test.ts",
    ],
    note:
      "Kernel idempotency, Gmail message/thread refs, sync retry behavior, and Supabase person linking are covered.",
  },
  {
    requirement: "Retention and deletion",
    status: "docs only",
    evidence: [
      "docs/plugin-data-safety.md",
      "tests/plugin_data_safety_docs.test.ts",
    ],
    note: "Deletion and retention flows are documented requirements but not yet runtime behavior.",
  },
  {
    requirement: "Plugin review checklist",
    status: "docs only",
    evidence: [
      "docs/plugin-data-safety.md",
      "tests/plugin_data_safety_docs.test.ts",
    ],
    note: "The checklist is documented and regression-tested as required plugin review language.",
  },
]

export function renderPluginSafetyCoverage(): string {
  return [
    "# Plugin Safety Coverage",
    "",
    "<!-- GENERATED by tools/generate_plugin_safety_docs.ts. Do not edit by hand. -->",
    "",
    "This document maps the Plugin Data Safety requirements to the current test coverage.",
    "",
    "| Requirement | Status | Evidence | Notes |",
    "| --- | --- | --- | --- |",
    ...rows.map((row) =>
      `| ${row.requirement} | ${row.status} | ${
        row.evidence.map((item) => `\`${item}\``).join("<br>")
      } | ${row.note} |`
    ),
    "",
    "## Summary",
    "",
    "- Runtime-tested: workspace isolation, explicit capabilities, secrets outside CRM, no raw provider payloads, auditable writes, redacted operational output, and idempotency/dedupe.",
    "- Partially runtime-tested: data minimization, because final minimization choices remain plugin-specific.",
    "- Docs-only today: retention/deletion behavior and the plugin review checklist.",
    "",
  ].join("\n")
}

if (import.meta.main) {
  await Deno.writeTextFile(
    "docs/generated/plugin-safety-coverage.md",
    renderPluginSafetyCoverage(),
  )
}
