type DocsPage = {
  title: string
  source: string
  target: string
}

type DocsGroup = {
  title: string
  pages: DocsPage[]
}

const generatedHeader = "<!-- GENERATED by tools/generate_docs_site.ts. Do not edit by hand. -->"

const startPages: DocsPage[] = [
  { title: "README", source: "README.md", target: "start/readme.md" },
  { title: "Contributing", source: "CONTRIBUTING.md", target: "start/contributing.md" },
  { title: "Install", source: "docs/install.md", target: "start/install.md" },
  { title: "Open Source Plan", source: "docs/open-source.md", target: "start/open-source.md" },
]

const groups: DocsGroup[] = [
  {
    title: "Core",
    pages: [
      { title: "Hard Rules", source: "docs/hard-rules.md", target: "core/hard-rules.md" },
      { title: "Architecture", source: "docs/architecture.md", target: "core/architecture.md" },
      { title: "Entities", source: "docs/entities.md", target: "core/entities.md" },
      { title: "Write API", source: "docs/write-api.md", target: "core/write-api.md" },
      { title: "Read API", source: "docs/read-api.md", target: "core/read-api.md" },
      { title: "Event Log", source: "docs/event-log.md", target: "core/event-log.md" },
      { title: "Storage API", source: "docs/storage-api.md", target: "core/storage-api.md" },
      { title: "SQLite", source: "docs/sqlite.md", target: "core/sqlite.md" },
      {
        title: "Postgres and Supabase",
        source: "docs/postgres-supabase.md",
        target: "core/postgres-supabase.md",
      },
      { title: "CLI", source: "docs/cli.md", target: "core/cli.md" },
      { title: "Admin Surface", source: "docs/admin-surface.md", target: "core/admin-surface.md" },
      { title: "Permissions", source: "docs/permissions.md", target: "core/permissions.md" },
      {
        title: "Privacy Safety",
        source: "docs/privacy-safety.md",
        target: "core/privacy-safety.md",
      },
      { title: "Conformance", source: "docs/conformance.md", target: "core/conformance.md" },
      {
        title: "Test Portfolio",
        source: "docs/test-portfolio.md",
        target: "core/test-portfolio.md",
      },
    ],
  },
  {
    title: "Advanced",
    pages: [
      {
        title: "Import and Export",
        source: "docs/import-export.md",
        target: "advanced/import-export.md",
      },
      {
        title: "Channel Strategy",
        source: "docs/channel-strategy.md",
        target: "advanced/channel-strategy.md",
      },
      {
        title: "App User Lookup",
        source: "docs/app-user-lookup.md",
        target: "advanced/app-user-lookup.md",
      },
      { title: "Gmail Plugin", source: "docs/gmail-plugin.md", target: "advanced/gmail-plugin.md" },
      {
        title: "Instagram Plugin",
        source: "docs/instagram-plugin.md",
        target: "advanced/instagram-plugin.md",
      },
      {
        title: "Reddit Plugin",
        source: "docs/reddit-plugin.md",
        target: "advanced/reddit-plugin.md",
      },
      {
        title: "Google Tasks Plugin",
        source: "docs/google-tasks-plugin.md",
        target: "advanced/google-tasks-plugin.md",
      },
      {
        title: "Granola Plugin",
        source: "docs/granola-plugin.md",
        target: "advanced/granola-plugin.md",
      },
      {
        title: "Policies and Workflows",
        source: "docs/policies-workflows.md",
        target: "advanced/policies-workflows.md",
      },
      { title: "Plugins", source: "docs/plugins.md", target: "advanced/plugins.md" },
      {
        title: "Plugin Development",
        source: "docs/plugin-development.md",
        target: "advanced/plugin-development.md",
      },
      {
        title: "Plugin Data Safety",
        source: "docs/plugin-data-safety.md",
        target: "advanced/plugin-data-safety.md",
      },
      {
        title: "Plugin Workbench UI",
        source: "docs/workbench-ui.md",
        target: "advanced/workbench-ui.md",
      },
      {
        title: "Plugin Safety Coverage",
        source: "docs/generated/plugin-safety-coverage.md",
        target: "advanced/plugin-safety-coverage.md",
      },
      {
        title: "Extension Host",
        source: "docs/extension-host.md",
        target: "advanced/extension-host.md",
      },
      { title: "MCP Adapter", source: "docs/mcp.md", target: "advanced/mcp.md" },
      { title: "Dashboard Lab", source: "docs/dashboard.md", target: "advanced/dashboard.md" },
      { title: "Noros Integration", source: "docs/noros.md", target: "advanced/noros.md" },
      { title: "Publishing", source: "docs/publishing.md", target: "advanced/publishing.md" },
    ],
  },
]

const allPages = [...startPages, ...groups.flatMap((group) => group.pages)]
const targetBySource = new Map(allPages.map((page) => [normalizePath(page.source), page.target]))

export type GeneratedDocsFile = {
  path: string
  content: string
}

export async function generateDocsSiteFiles(): Promise<GeneratedDocsFile[]> {
  const files: GeneratedDocsFile[] = [
    { path: "docs-site/src/index.md", content: renderHomePage() },
    { path: "docs-site/src/quickstart.md", content: renderQuickstartPage() },
    { path: "docs-site/.vitepress/config.mts", content: renderVitePressConfig() },
    { path: "docs-site/README.md", content: renderDocsSiteReadme() },
  ]

  for (const page of allPages) {
    const source = await Deno.readTextFile(page.source)
    files.push({
      path: `docs-site/src/${page.target}`,
      content: `${generatedHeader}\n\n${rewriteMarkdownLinks(source, page.source)}\n`,
    })
  }

  return files
}

async function writeGeneratedFiles(files: GeneratedDocsFile[]) {
  for (const file of files) {
    await Deno.mkdir(dirname(file.path), { recursive: true })
    await Deno.writeTextFile(file.path, file.content)
  }
}

async function checkGeneratedFiles(files: GeneratedDocsFile[]): Promise<number> {
  const stale: string[] = []

  for (const file of files) {
    let current = ""
    try {
      current = await Deno.readTextFile(file.path)
    } catch {
      stale.push(file.path)
      continue
    }
    if (current !== file.content) stale.push(file.path)
  }

  if (stale.length > 0) {
    console.error([
      "Docs site is stale. Run:",
      "",
      "  deno task docs:site",
      "",
      "Stale files:",
      ...stale.map((file) => `- ${file}`),
    ].join("\n"))
    return 1
  }

  console.log("Docs site is current.")
  return 0
}

function renderHomePage(): string {
  return [
    "---",
    "layout: home",
    "",
    "hero:",
    "  name: Bare CRM",
    "  text: Tiny CRM kernel",
    "  tagline: Stable CRM facts, explicit APIs, boring storage, and optional extensions.",
    "  actions:",
    "    - theme: brand",
    "      text: Quickstart",
    "      link: /quickstart",
    "    - theme: alt",
    "      text: Architecture",
    "      link: /core/architecture",
    "    - theme: alt",
    "      text: GitHub",
    "      link: https://github.com/danekm/bare-crm",
    "",
    "features:",
    "  - title: Kernel first",
    "    details: Write API, Read API, Event Log, and Storage API stay small and stable.",
    "  - title: Local by default",
    "    details: The CLI and storage adapters work without a hosted control plane.",
    "  - title: Extensible outside the core",
    "    details: Plugins, workflows, dashboards, and agents stay optional and explicit.",
    "---",
    "",
    generatedHeader,
    "",
    "## Start Here",
    "",
    "- [Quickstart](/quickstart)",
    "- [README](/start/readme)",
    "- [Install](/start/install)",
    "- [Hard Rules](/core/hard-rules)",
    "",
  ].join("\n")
}

function renderQuickstartPage(): string {
  return [
    generatedHeader,
    "",
    "# Quickstart",
    "",
    "Bare CRM is a small kernel for durable CRM facts. Start with the library, then add storage or",
    "operator tooling only when you need it.",
    "",
    "## Install",
    "",
    "```sh",
    "deno add jsr:@bare-crm/kernel",
    "```",
    "",
    "## Use the Kernel",
    "",
    "```ts",
    'import { createCrmKernel } from "@bare-crm/kernel"',
    "",
    "const crm = createCrmKernel()",
    "",
    'await crm.write("person.create", {',
    '  workspaceId: "workspace_1",',
    '  name: "Ada Lovelace",',
    '  emails: [{ value: "ada@example.com", primary: true }],',
    "})",
    "",
    'const people = await crm.read("record.search", {',
    '  workspaceId: "workspace_1",',
    '  type: "person",',
    '  text: "ada",',
    "})",
    "```",
    "",
    "## Add SQLite",
    "",
    "```ts",
    'import { createCrmKernel } from "@bare-crm/kernel"',
    'import { createSqliteStorage } from "@bare-crm/kernel/sqlite"',
    "",
    'const storage = createSqliteStorage("./bare-crm.db")',
    "const crm = createCrmKernel({ storage })",
    "```",
    "",
    "## Use the CLI",
    "",
    "```sh",
    "crm doctor",
    "crm db status sqlite ./bare-crm.db",
    "crm plugins validate ./plugin.json",
    "```",
    "",
    "Next: [Architecture](/core/architecture) and [Write API](/core/write-api).",
    "",
  ].join("\n")
}

function renderDocsSiteReadme(): string {
  return [
    "# Bare CRM Docs Site",
    "",
    "Generated VitePress documentation site.",
    "",
    "Do not edit files under `docs-site/src/` or `docs-site/.vitepress/config.mts` by hand.",
    "Update `README.md`, `docs/`, or the generator, then run:",
    "",
    "```sh",
    "deno task docs:site",
    "npm install --prefix docs-site",
    "npm run docs:build --prefix docs-site",
    "```",
    "",
  ].join("\n")
}

function renderVitePressConfig(): string {
  const sidebarGroups = [
    {
      text: "Start Here",
      items: [
        { text: "Quickstart", link: "/quickstart" },
        ...startPages.map(sidebarItem),
      ],
    },
    ...groups.map((group) => ({
      text: group.title,
      collapsed: group.title === "Advanced",
      items: group.pages.map(sidebarItem),
    })),
  ]

  return [
    "// GENERATED by tools/generate_docs_site.ts. Do not edit by hand.",
    "",
    'import { defineConfig } from "vitepress"',
    "",
    "export default defineConfig({",
    '  title: "Bare CRM",',
    '  description: "Tiny CRM kernel with stable APIs and optional extensions.",',
    '  base: process.env.DOCS_BASE ?? "/bare-crm/",',
    '  srcDir: "src",',
    "  cleanUrls: true,",
    "  lastUpdated: true,",
    "  vite: {",
    "    build: {",
    '      target: "esnext",',
    "    },",
    "  },",
    "  themeConfig: {",
    "    logo: undefined,",
    "    nav: [",
    '      { text: "Guide", link: "/quickstart" },',
    '      { text: "Core", link: "/core/architecture" },',
    '      { text: "Advanced", link: "/advanced/plugins" },',
    '      { text: "GitHub", link: "https://github.com/danekm/bare-crm" },',
    "    ],",
    `    sidebar: ${JSON.stringify(sidebarGroups, null, 6).replace(/^/gm, "    ").trimStart()},`,
    "    search: {",
    '      provider: "local",',
    "    },",
    "    socialLinks: [",
    '      { icon: "github", link: "https://github.com/danekm/bare-crm" },',
    "    ],",
    "  },",
    "})",
    "",
  ].join("\n")
}

function sidebarItem(page: DocsPage) {
  return {
    text: page.title,
    link: `/${page.target.replace(/\.md$/, "")}`,
  }
}

function rewriteMarkdownLinks(content: string, sourcePath: string): string {
  return content.replace(/\]\(([^)\s]+?\.md)(#[^)]+)?\)/g, (match, rawLink, anchor = "") => {
    if (/^https?:\/\//.test(rawLink)) return match
    const resolved = normalizePath(joinPath(dirname(sourcePath), rawLink))
    const target = targetBySource.get(resolved)
    if (!target) return match
    return `](/${target.replace(/\.md$/, "")}${anchor})`
  })
}

function normalizePath(path: string): string {
  const parts: string[] = []
  for (const part of path.split("/")) {
    if (!part || part === ".") continue
    if (part === "..") parts.pop()
    else parts.push(part)
  }
  return parts.join("/")
}

function joinPath(base: string, path: string): string {
  return normalizePath(`${base}/${path}`)
}

function dirname(path: string): string {
  const index = path.lastIndexOf("/")
  return index === -1 ? "." : path.slice(0, index)
}

if (import.meta.main) {
  const files = await generateDocsSiteFiles()
  Deno.exit(
    Deno.args.includes("--check") ? await checkGeneratedFiles(files) : await writeAndReport(files),
  )
}

async function writeAndReport(files: GeneratedDocsFile[]): Promise<number> {
  await writeGeneratedFiles(files)
  console.log(`Generated ${files.length} docs site files.`)
  return 0
}
